#!/usr/local/sbin/charm-env python3

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import base64
import json
import os
import kafkautils
import subprocess

from charmhelpers.core import hookenv, host
from charms.reactive import is_state

from charms.layer.kafka import KAFKA_SERVICE, KAFKA_APP_DATA


if not is_state('kafka.started'):
    kafkautils.fail('Kafka service not yet ready')


# Grab the business
topicfilecontent = json.loads(base64.b64decode(hookenv.action_get('topics-json')).decode("utf-8"))
broker = hookenv.action_get('broker')
ssl_properties = os.path.join(KAFKA_APP_DATA, 'client-ssl.properties')
with open('/tmp/topics-to-move-json-file', 'w') as outfile:
    json.dump(topicfilecontent, outfile)

# Write to the topic if kafka is running
if host.service_available(KAFKA_SERVICE) and host.service_running(KAFKA_SERVICE):
    zookeepers = kafkautils.get_zookeepers()
    try:
        output = subprocess.check_output(['/usr/lib/kafka/bin/kafka-reassign-partitions.sh',
                              '--generate',
                              '--topics-to-move-json-file', '/tmp/topics-to-move-json-file',
                              '--broker-list', broker,
                              '--zookeeper', zookeepers])
    except subprocess.CalledProcessError as e:
        kafkautils.fail('Kafka command failed: {}'.format(e.output))
    else:
        hookenv.action_set({'raw': output})
        hookenv.action_set({'outcome': 'success'})
else:
    kafkautils.fail('kafka-server service is not running')
