#!/usr/local/sbin/charm-env python3

import kafkautils

from charmhelpers.core import hookenv

from charms.reactive import remove_state

from charms import apt


if not hookenv.config().get('inter_broker_protocol_version'):
    kafkautils.fail('inter_broker_protocol_version not configured')

remove_state('kafka.nrpe_helper.installed')
remove_state('kafka.started')
remove_state('apt.installed.kafka')
remove_state('apt.queued_installs')

hookenv.function_set({'outcome': 'success'})
