options:
  # Broker options
  auto_create_topics:
    default: true
    type: boolean
    description: |-
      Enable auto creation of topic on the server (auto.create.topics.enable)
  default_partitions:
    default: 1
    type: int
    description: |-
      The default number of log partitions per topic (num.partitions)
  default_replication_factor:
    default: 1
    type: int
    description: |-
      Default replication factor for automatically created topics
      (default.replication.factor)
  extra_config:
    default: |-
      "bnVtLm5ldHdvcmsudGhyZWFkcz0zCm51bS5pby50aHJlYWRzPTgKc29ja2V0LnNlbmQuYnVmZmVy
       LmJ5dGVzPTEwMjQwMApzb2NrZXQucmVjZWl2ZS5idWZmZXIuYnl0ZXM9MTAyNDAwCnNvY2tldC5y
       ZXF1ZXN0Lm1heC5ieXRlcz0xMDQ4NTc2MDAKbnVtLnJlY292ZXJ5LnRocmVhZHMucGVyLmRhdGEu
       ZGlyPTEKb2Zmc2V0cy50b3BpYy5yZXBsaWNhdGlvbi5mYWN0b3I9MQp0cmFuc2FjdGlvbi5zdGF0
       ZS5sb2cucmVwbGljYXRpb24uZmFjdG9yPTEKdHJhbnNhY3Rpb24uc3RhdGUubG9nLm1pbi5pc3I9
       MQpsb2cucmV0ZW50aW9uLmhvdXJzPTE2OApsb2cuc2VnbWVudC5ieXRlcz0xMDczNzQxODI0Cmxv
       Zy5yZXRlbnRpb24uY2hlY2suaW50ZXJ2YWwubXM9MzAwMDAwCnpvb2tlZXBlci5jb25uZWN0aW9u
       LnRpbWVvdXQubXM9NjAwMApncm91cC5pbml0aWFsLnJlYmFsYW5jZS5kZWxheS5tcz0wCgoK"
    type: string
    description: |-
      Base 64 encodede string for server properties tuning file.

  # TLS options
  subject_alt_names:
    default: ""
    type: string
    description: |-
      Additional subject alternate names (SANs) that should be added to the
      server certificate requested from the CA. Specified as a comma-separated list
      of hostnames and/or IP addresses.

  # Nagios options
  nagios_context:
    default: juju
    type: string
    description: |-
      Used by the nrpe subordinate charms.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
          juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: |-
      A comma-separated list of nagios servicegroups.
      If left empty, the nagios_context will be used as the servicegroup
  nagios_leader_election_rate_warn:
    type: string
    default: '100'
    description: |-
      The warning threshold for the leader election rate and latency in ms.
  nagios_leader_election_rate_crit:
    type: string
    default: '1000'
    description: |-
      The critical threshold for the leader election rate and latency in ms.
  nagios_producer_time_warn:
    type: string
    default: '50'
    description: |-
      The warning threshold for the 99th percentile time it takes to produce a message.
  nagios_producer_time_crit:
    type: string
    default: '500'
    description: |-
      The critical threshold for the 99th percentile time it takes to produce a message.
  nagios_consumer_fetch_time_warn:
    type: string
    default: '50'
    description: |-
      The warning threshold for the 99th percentile time it takes for a consumer to fetch a message.
  nagios_consumer_fetch_time_crit:
    type: string
    default: '500'
    description: |-
      The critical threshold for the 99th percentile time it takes for a consumer to fetch a message.
  nagios_avg_network_processor_idle_warn:
    type: string
    default: '.20'
    description: |-
      The warning threshold for average idle percentage of a network processor
  nagios_avg_network_processor_idle_crit:
    type: string
    default: '.10'
    description: |-
      The critical threshold for average idle percentage of a network processor
  port:
    type: int
    default: 9093
    description: |-
      Port to run the Kafka services on
  log_dir:
    type: string
    default: '/var/lib/kafka/logs'
    description: |-
      This option will use the driectory for logs. In case of MAAS deployment
      we should preconfigured the mount point.
  service_environment:
    type: string
    default: 'KAFKA_HEAP_OPTS=-Xmx1G -Xms128M'
    description: |-
      This option will define the kafka service environment will into service section.
  service_parameter:
    type: string
    default: 'LimitNOFILE=128000'
    description: |-
      This option will define the extra kafka service parameters into service section.
  inter_broker_protocol_version:
    type: string
    default: ''
    description: |-
      Specify the message format version the broker will use to append messages
      to the logs. If set to empty string, the current broker version is used. This
      setting is useful for coordinating kafka broker upgrades.
  log_message_format_version:
    type: string
    default: ''
    description: |-
      Specify the message format version the broker will use to append messages
      to the logs. If set to empty string, the current broker version is used. This
      setting is useful for coordinating kafka broker upgrades.
  log4j_properties:
    default: ""
    type: string
    description: |-
      Contents of a custom log4j.properties file for the Kafka brokers. If
      empty, the default will be used instead.
